name: Tests

on:
  workflow_dispatch:
  push:
    paths:
      - api/**
      - api_tests/**
    branches: [ "main" ]

jobs:

  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: docker compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from api-test
